# Generated by Django 3.1.5 on 2021-01-06 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvodjac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tastatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('cena_DIN', models.IntegerField(default=0)),
                ('proizvedeno_Od', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tastatura.proizvodjac')),
            ],
        ),
    ]
